### ISSUE TITLE
Package ?

### ISSUE THREAD

**Issue by teytaud** [AlgTUDelft/ExpensiveOptimBenchmark#11]
Hello! I work on Nevergrad.
We would like to interface our platform with your benchmarks.
Would it be possible to package your tools, so that we can import it inside Nevergrad and run all this in our dashboard (https://dl.fbaipublicfiles.com/nevergrad/allxps/list.html) ?
This would lead to all your benchmarks to be used in tests of many optimization methods (not only Nevergrad).

**Comment by CarolaDoerr** [comment]
Just adding a comment, in the hope that I will see answers :-) (don''t understand yet how GitHub works)

**Comment by lbliek** [comment]
Hi! Thanks for your question, I've sent you an e-mail to ask for some clarifications, but I will put the final answer here for anyone who is interested.

**Comment by lbliek** [comment]
So the short answer is that we cannot easily package this library unfortunately, as not all methods are written in python, and some problems make use of Docker. If anyone has any more ideas we would be happy to discuss, as it would be interesting to compare with the tools of Nevergrad.
